[2023-12-16T18:17:06.392+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T18:10:27.755436+00:00 [queued]>
[2023-12-16T18:17:06.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T18:10:27.755436+00:00 [queued]>
[2023-12-16T18:17:06.399+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 1
[2023-12-16T18:17:06.457+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): visualization> on 2023-12-16 18:10:27.755436+00:00
[2023-12-16T18:17:06.462+0000] {standard_task_runner.py:57} INFO - Started process 907 to run task
[2023-12-16T18:17:06.465+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_data_pipeline', 'visualization', 'manual__2023-12-16T18:10:27.755436+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/taxi_etl.py', '--cfg-path', '/tmp/tmp62l78sye']
[2023-12-16T18:17:06.467+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask visualization
[2023-12-16T18:17:06.506+0000] {task_command.py:416} INFO - Running <TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T18:10:27.755436+00:00 [running]> on host 1956fcd736af
[2023-12-16T18:17:06.568+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='islam' AIRFLOW_CTX_DAG_ID='NYC_Taxi_data_pipeline' AIRFLOW_CTX_TASK_ID='visualization' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T18:10:27.755436+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T18:10:27.755436+00:00'
[2023-12-16T18:17:10.893+0000] {logging_mixin.py:154} INFO - Dash is running on http://0.0.0.0:8050/
[2023-12-16T18:17:10.893+0000] {dash.py:2053} INFO - Dash is running on http://0.0.0.0:8050/

[2023-12-16T18:17:10.898+0000] {logging_mixin.py:154} INFO -  * Serving Flask app '***'
[2023-12-16T18:17:10.898+0000] {logging_mixin.py:154} INFO -  * Debug mode: off
[2023-12-16T18:17:10.899+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.24.0.3:8050
[2023-12-16T18:17:10.900+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-12-16T18:17:50.691+0000] {_internal.py:224} INFO - 172.24.0.1 - - [16/Dec/2023 18:17:50] "POST /_dash-update-component HTTP/1.1" 200 -
[2023-12-16T18:17:52.852+0000] {_internal.py:224} INFO - 172.24.0.1 - - [16/Dec/2023 18:17:52] "POST /_dash-update-component HTTP/1.1" 200 -
[2023-12-16T18:25:29.569+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-12-16T18:25:29.572+0000] {process_utils.py:131} INFO - Sending 15 to group 907. PIDs of all processes in the group: [907]
[2023-12-16T18:25:29.573+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 907
[2023-12-16T18:25:29.574+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-16T18:25:29.593+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dashboard.py", line 220, in create_dashboard
    app.run_server(host='0.0.0.0', debug=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/dash/dash.py", line 2175, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/dash/dash.py", line 2076, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1069, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.8/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-12-16T18:25:29.621+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=NYC_Taxi_data_pipeline, task_id=visualization, execution_date=20231216T181027, start_date=20231216T181706, end_date=20231216T182529
[2023-12-16T18:25:29.641+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task visualization (Task received SIGTERM signal; 907)
[2023-12-16T18:25:29.670+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=907, status='terminated', exitcode=1, started='18:17:05') (907) terminated with exit code 1
[2023-12-16T18:25:29.671+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2023-12-16T18:25:29.689+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
