[2023-12-16T18:42:35.341+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T18:42:04.792767+00:00 [queued]>
[2023-12-16T18:42:35.351+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T18:42:04.792767+00:00 [queued]>
[2023-12-16T18:42:35.352+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-16T18:42:35.368+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): visualization> on 2023-12-16 18:42:04.792767+00:00
[2023-12-16T18:42:35.374+0000] {standard_task_runner.py:57} INFO - Started process 370 to run task
[2023-12-16T18:42:35.377+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_data_pipeline', 'visualization', 'manual__2023-12-16T18:42:04.792767+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/taxi_etl.py', '--cfg-path', '/tmp/tmp0rf_wb0k']
[2023-12-16T18:42:35.380+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask visualization
[2023-12-16T18:42:35.427+0000] {task_command.py:416} INFO - Running <TaskInstance: NYC_Taxi_data_pipeline.visualization manual__2023-12-16T18:42:04.792767+00:00 [running]> on host 40ff33ca59cb
[2023-12-16T18:42:35.500+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='islam' AIRFLOW_CTX_DAG_ID='NYC_Taxi_data_pipeline' AIRFLOW_CTX_TASK_ID='visualization' AIRFLOW_CTX_EXECUTION_DATE='2023-12-16T18:42:04.792767+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-16T18:42:04.792767+00:00'
[2023-12-16T18:42:38.217+0000] {logging_mixin.py:154} INFO - Dash is running on http://0.0.0.0:8050/
[2023-12-16T18:42:38.217+0000] {dash.py:2053} INFO - Dash is running on http://0.0.0.0:8050/

[2023-12-16T18:42:38.227+0000] {logging_mixin.py:154} INFO -  * Serving Flask app '***'
[2023-12-16T18:42:38.228+0000] {logging_mixin.py:154} INFO -  * Debug mode: off
[2023-12-16T18:42:38.229+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.26.0.4:8050
[2023-12-16T18:42:38.229+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2023-12-16T18:42:55.655+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:42:55] "GET / HTTP/1.1" 200 -
[2023-12-16T18:42:55.811+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:42:55] "GET /_dash-dependencies HTTP/1.1" 200 -
[2023-12-16T18:42:55.818+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:42:55] "GET /_dash-layout HTTP/1.1" 200 -
[2023-12-16T18:42:55.848+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:42:55] "[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1[0m" 304 -
[2023-12-16T18:42:55.860+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:42:55] "[36mGET /_dash-component-suites/plotly/package_data/plotly.min.js HTTP/1.1[0m" 304 -
[2023-12-16T18:42:57.424+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:42:57] "POST /_dash-update-component HTTP/1.1" 200 -
[2023-12-16T18:43:34.731+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:43:34] "POST /_dash-update-component HTTP/1.1" 200 -
[2023-12-16T18:43:40.449+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:43:40] "POST /_dash-update-component HTTP/1.1" 200 -
[2023-12-16T18:43:44.669+0000] {_internal.py:224} INFO - 172.26.0.1 - - [16/Dec/2023 18:43:44] "POST /_dash-update-component HTTP/1.1" 200 -
[2023-12-16T18:52:39.393+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-12-16T18:52:39.397+0000] {process_utils.py:131} INFO - Sending 15 to group 370. PIDs of all processes in the group: [370]
[2023-12-16T18:52:39.398+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 370
[2023-12-16T18:52:39.399+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-16T18:52:39.423+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dashboard.py", line 220, in create_dashboard
    app.run_server(host='0.0.0.0', debug=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/dash/dash.py", line 2175, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/dash/dash.py", line 2076, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1069, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.8/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-12-16T18:52:39.431+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=NYC_Taxi_data_pipeline, task_id=visualization, execution_date=20231216T184204, start_date=20231216T184235, end_date=20231216T185239
[2023-12-16T18:52:39.452+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task visualization (Task received SIGTERM signal; 370)
[2023-12-16T18:52:39.497+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=370, status='terminated', exitcode=1, started='18:42:34') (370) terminated with exit code 1
[2023-12-16T18:52:39.498+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2023-12-16T18:52:39.514+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
